apiVersion: v1
kind: Service
metadata:
  labels:
    name: entrance-db
    type: db
  name: entrance-db
  namespace: prototype
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: tcp
  selector:
    name: entrance-db
    type: db
