version: '3'
services:
  company-server:
    build: ./
    command: npm run start
    volumes:
      - .:/usr/src/app/
    ports:
      - "50054:50051"
    links:
      - company-db:mongo
    depends_on:
      - company-db
  company-db:
    image: mongo
    ports:
      - "27020:27017"
