version: '3'
services:
  pulse-client:
    build: ./
    command: npm run start
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
    external_links:
      - lotserver_lot-server_1:lot-server
      - entranceserver_entrance-server_1:entrance-server
      - laneserver_lane-server_1:lane-server
      - companyserver_company-server_1:company-server
      - sensorserver_sensor-server_1:sensor-server
    networks:
      - default
      - entrance-server
      - lane-server
      - company-server
      - sensor-server
networks:
  default:
    external:
      name: lotserver_default
  entrance-server:
    external:
      name: entranceserver_default
  lane-server:
    external:
      name: laneserver_default
  company-server:
    external:
      name: sensorserver_default
  sensor-server:
    external:
      name: sensorserver_default
