version: '3'
services:
  lane-server:
    build: ./
    command: npm run start
    volumes:
      - .:/usr/src/app/
    ports:
      - "50053:50051"
    links:
      - lane-db:mongo
    depends_on:
      - lane-db
  lane-db:
    image: mongo
    ports:
      - "27019:27017"
