apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: lane-db
    type: db
  name: lane-db
  namespace: prototype
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: lane-db
        type: db
    spec:
      containers:
      - image: mongo
        name: lane-db
        ports:
         - containerPort: 27017
           name: lane-db
        volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          emptyDir: {}
