apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongodb 
    type: db
  name: mongodb
  namespace: deploy-tracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
        type: db
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
         - containerPort: 27017
           name: mongodb
        volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          emptyDir: {}
