version: '3'
services:
  entrance-server:
    build: ./
    command: npm run start
    volumes:
      - .:/usr/src/app/
    ports:
      - "50052:50051"
    links:
      - entrance-db:mongo
    depends_on:
      - entrance-db
  entrance-db:
    image: mongo
    ports:
      - "27018:27017"
