apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: status-client
  namespace: deploy-tracker
  annotations:
    kubernetes.io/ingress.class: "linkerd"
spec:
  rules:
  - host: services.parkhub.com
    http:
      paths:
      - path: /status/.*
        backend:
          serviceName: status-client
          servicePort: http
