apiVersion: v1
kind: Service
metadata:
  labels:
    name: status-client
    type: api
  name: status-client 
  namespace: deploy-tracker
spec:
  clusterIP: None
  ports: 
    - port: 3000
      name: http
  selector:
    name: status-client
    type: api



